import clsx from "clsx";

import type { CollectionDoc } from "@main/api-studio/docs/types";

interface DocDesignPreviewProps {
  doc: CollectionDoc;
}

const PAPER = { ink: "#16202b", muted: "#5b6b7c", line: "#e2e8f0", soft: "#f7f9fc" };
const RATIO: Record<string, string> = { A4: "210 / 297", Letter: "8.5 / 11" };
const PADDING: Record<string, string> = { narrow: "10px", normal: "16px", wide: "22px" };

/** The artifact, not the app: this sheet keeps the document's own palette. */
export function DocDesignPreview({ doc }: Readonly<DocDesignPreviewProps>) {
  const { theme } = doc;
  const rule = { backgroundColor: PAPER.line };

  return (
    <div className="flex w-[15rem] shrink-0 flex-col gap-2">
      <span className="text-[10px] font-semibold uppercase tracking-wide text-muted">
        {doc.theme.pageSize} · {doc.title || "Untitled"}
      </span>

      <div
        className="overflow-hidden rounded-xl border border-border bg-white"
        style={{ aspectRatio: RATIO[theme.pageSize] }}
      >
        <div
          className="flex h-full flex-col gap-[7px]"
          style={{ padding: PADDING[theme.margin], color: PAPER.ink }}
        >
          {theme.logo ? (
            <img src={theme.logo} alt="" className="h-3.5 w-auto self-start object-contain" />
          ) : null}

          {theme.cover ? (
            <>
              <span
                className="text-[5px] font-bold uppercase tracking-[0.14em]"
                style={{ color: theme.accent }}
              >
                API documentation
              </span>
              <span className="text-[13px] font-bold leading-tight">
                {doc.title || "Untitled"}
              </span>
              {doc.subtitle ? (
                <span className="text-[6px] leading-snug" style={{ color: PAPER.muted }}>
                  {doc.subtitle}
                </span>
              ) : null}
            </>
          ) : (
            <span className="text-[11px] font-bold leading-tight">{doc.title || "Untitled"}</span>
          )}

          <div className="h-px w-full" style={rule} />

          <div className="flex gap-3 text-[5px]" style={{ color: PAPER.muted }}>
            <span>{doc.version || "1.0.0"}</span>
            <span className="truncate">{doc.baseUrl || "https://api.example.com"}</span>
          </div>

          <div className="flex min-h-0 flex-1 gap-2">
            {theme.contents ? (
              <div className="flex w-[26%] shrink-0 flex-col gap-[3px] pt-[2px]">
                {["Overview", "Authentication", "Payments"].map((line) => (
                  <span key={line} className="truncate text-[5px]" style={{ color: PAPER.muted }}>
                    {line}
                  </span>
                ))}
              </div>
            ) : null}

            <div className="flex min-w-0 flex-1 flex-col gap-[4px]">
              <div className="flex items-baseline gap-1">
                <span className="text-[6px] font-bold" style={{ color: "#b45309" }}>
                  POST
                </span>
                <span className="text-[7px] font-semibold">Create a payment</span>
              </div>

              <div
                className="rounded-[3px] px-1 py-[3px] text-[5px]"
                style={{ background: PAPER.soft, border: `1px solid ${PAPER.line}` }}
              >
                /payments
              </div>

              {theme.curl ? (
                <div
                  className={clsx("rounded-[3px] px-1 py-[4px] font-mono text-[4.5px] leading-[1.6]")}
                  style={{
                    background: theme.darkCode ? "#0f172a" : PAPER.soft,
                    color: theme.darkCode ? "#e2e8f0" : PAPER.ink,
                    border: `1px solid ${theme.darkCode ? "#1e293b" : PAPER.line}`
                  }}
                >
                  curl -X POST &apos;/payments&apos;
                </div>
              ) : null}

              {theme.examples ? (
                <div className="flex items-center gap-1">
                  <span className="text-[5px] font-bold" style={{ color: "#2f855a" }}>
                    201
                  </span>
                  <span className="text-[5px]" style={{ color: PAPER.muted }}>
                    application/json
                  </span>
                </div>
              ) : null}
            </div>
          </div>

          <div className="h-px w-full" style={rule} />
          <span className="text-[4.5px]" style={{ color: PAPER.muted }}>
            Generated by Lazify
          </span>
        </div>
      </div>
    </div>
  );
}
