import fs from "node:fs";
import os from "node:os";
import path from "node:path";

type ListAgentSessions = (projectPath: string, limit?: number) => Promise<unknown>;

const jsonl = (...records: unknown[]) => records.map((record) => JSON.stringify(record)).join("\n");

const user = (content: unknown, extra: Record<string, unknown> = {}) => ({ type: "user", message: { content }, ...extra });

const CHUNK = 64 * 1024;
const snapshot = { type: "file-history-snapshot", files: "s".repeat(CHUNK + 1234) };
const straddling = (() => {
	const prompt = JSON.stringify(user("café ☕ — résumé naïve 日本語 prompt"));
	const intoCup = Buffer.byteLength(prompt.slice(0, prompt.indexOf("☕"))) + 1;
	const padding = CHUNK - intoCup - 1 - JSON.stringify({ type: "summary", pad: "" }).length;
	return `${JSON.stringify({ type: "summary", pad: "p".repeat(padding) })}\n${prompt}`;
})();

const CLAUDE_FILES: Record<string, { body: string; mtime: number }> = {
	"older.jsonl": {
		body: jsonl(
			snapshot,
			user("<command-name>/clear</command-name>"),
			user("Caveat: the messages below were generated by the user"),
			user("Sidechain work", { isSidechain: true }),
			user("Fix the login bug\n\n   when the token\texpires"),
		),
		mtime: 1_700_000_100,
	},
	"blocks.jsonl": {
		body: jsonl(
			user([
				{ type: "image", source: { data: "..." } },
				{ type: "text", text: "Why does" },
				{ type: "text", text: "this screenshot look off?" },
			]),
		),
		mtime: 1_700_000_400,
	},
	"tools-only.jsonl": {
		body: jsonl(user([{ type: "tool_result", content: "ok" }]), { type: "assistant", message: { content: "hi" } }),
		mtime: 1_700_000_200,
	},
	"long-crlf.jsonl": {
		body: [JSON.stringify({ type: "system" }), JSON.stringify(user(`# Heading\n${"x".repeat(10)}`)), JSON.stringify(user("Explain ".repeat(40)))].join("\r\n"),
		mtime: 1_700_000_300,
	},
	"unicode.jsonl": { body: straddling, mtime: 1_700_000_500 },
	"truncated.jsonl": { body: `${JSON.stringify(user("<system>"))}\n{"type":"user","message":{"content":"cut off`, mtime: 1_700_000_050 },
	"notes.txt": { body: "not a transcript", mtime: 1_700_000_900 },
};

const CODEX_FILES: Record<string, { body: string; mtime: number }> = {
	"2026/10/08/rollout-new.jsonl": {
		body: jsonl(
			{ type: "session_meta", payload: { id: "codex-new", cwd: "/work/web" } },
			{ type: "response_item", payload: { role: "user", content: [{ type: "input_text", text: "<environment_context>" }] } },
			{ type: "event_msg", payload: { type: "user_message", message: "Add a dark mode toggle" } },
		),
		mtime: 1_700_000_450,
	},
	"2026/10/07/rollout-old-format.jsonl": {
		body: jsonl(
			{ type: "session_meta", payload: { cwd: "/work/web" } },
			{
				type: "response_item",
				payload: {
					role: "user",
					content: [
						{ type: "input_text", text: "<user_instructions>be terse</user_instructions>" },
						{ type: "input_text", text: "Write tests   for the parser" },
					],
				},
			},
		),
		mtime: 1_700_000_350,
	},
	"2026/10/07/rollout-elsewhere.jsonl": {
		body: jsonl({ type: "session_meta", payload: { id: "codex-other", cwd: "/work/api" } }, user("other project")),
		mtime: 1_700_000_600,
	},
	"2026/10/06/rollout-no-meta.jsonl": {
		body: jsonl({ type: "event_msg", payload: { type: "user_message", message: "No meta" } }),
		mtime: 1_700_000_700,
	},
	"2026/10/06/deeper/than/allowed/rollout-deep.jsonl": {
		body: jsonl({ type: "session_meta", payload: { id: "too-deep", cwd: "/work/web" } }),
		mtime: 1_700_000_800,
	},
};

function writeTree(root: string, files: Record<string, { body: string; mtime: number }>) {
	for (const [relative, { body, mtime }] of Object.entries(files)) {
		const file = path.join(root, relative);
		fs.mkdirSync(path.dirname(file), { recursive: true });
		fs.writeFileSync(file, body);
		fs.utimesSync(file, mtime, mtime);
	}
}

export async function exercise(listAgentSessions: ListAgentSessions): Promise<Record<string, unknown>> {
	const home = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "agent-sessions-")));
	const previousHome = process.env.HOME;

	writeTree(path.join(home, ".claude", "projects", "-work-web"), CLAUDE_FILES);
	writeTree(path.join(home, ".codex", "sessions"), CODEX_FILES);
	const empty = fs.mkdtempSync(path.join(os.tmpdir(), "agent-sessions-empty-"));

	try {
		process.env.HOME = home;
		const results: Record<string, unknown> = {
			all: await listAgentSessions("/work/web"),
			limited: await listAgentSessions("/work/web", 3),
			otherProject: await listAgentSessions("/work/api"),
			neverRun: await listAgentSessions("/work/none"),
		};

		process.env.HOME = empty;
		results.noTranscripts = await listAgentSessions("/work/web");

		return results;
	} finally {
		process.env.HOME = previousHome;
		fs.rmSync(home, { recursive: true, force: true });
		fs.rmSync(empty, { recursive: true, force: true });
	}
}
