import { registerAgentHandlers } from "./agents";
import { registerApiDocHandlers } from "./api-docs";
import { registerApiStudioHandlers } from "./api-studio";
import { registerBrowserHandlers } from "./browser";
import { registerCodeIntelligenceHandlers } from "./code-intelligence";
import type { IpcContext } from "./context";
import { registerDmgHandlers } from "./dmg";
import { registerEnvFileHandlers } from "./env";
import { registerEnvironmentHandlers } from "./environment";
import { registerExtensionHandlers } from "./extensions";
import { registerFormattingHandlers } from "./formatting";
import { registerGitHandlers } from "./git";
import { registerLintingHandlers } from "./linting";
import { registerMediaHandlers } from "./media";
import { registerPackageHandlers } from "./packages";
import { registerProjectHandlers } from "./projects";
import { registerPromptHandlers } from "./prompts";
import { registerScriptHandlers } from "./scripts";
import { registerSystemHandlers } from "./system";
import { registerTaskHandlers } from "./tasks";
import { registerTemplateHandlers } from "./templates";
import { registerUpdaterHandlers } from "./updater";
import { registerWorkflowHandlers } from "./workflow";

export type { IpcContext };

export function registerDomainHandlers(ctx: IpcContext) {
	registerWorkflowHandlers(ctx);
	registerEnvironmentHandlers();
	registerEnvFileHandlers();
	registerTemplateHandlers();
	registerProjectHandlers(ctx);
	registerUpdaterHandlers();
	registerGitHandlers();
	registerScriptHandlers(ctx);
	registerAgentHandlers(ctx);
	registerCodeIntelligenceHandlers();
	registerSystemHandlers(ctx);
	registerDmgHandlers(ctx);
	registerBrowserHandlers();
	registerMediaHandlers();
	registerPackageHandlers(ctx);
	registerPromptHandlers();
	registerApiStudioHandlers(ctx);
	registerApiDocHandlers(ctx);
	registerTaskHandlers();
	registerFormattingHandlers();
	registerLintingHandlers(ctx);
	registerExtensionHandlers();
}
