import * as agents from "./agents";
import * as autopilot from "./autopilot";
import * as commands from "./commands";
import * as formatting from "./formatting";
import * as git from "./git";
import * as keepAwakeGroup from "./keep-awake";
import * as packages from "./packages";
import type { LazifyApi } from "./lazify-api";
import * as projects from "./projects";
import * as prompts from "./prompts";
import * as scripts from "./scripts";
import * as system from "./system";
import * as tasks from "./tasks";
import * as workflow from "./workflow";
import * as zoom from "./zoom";

const unported = {
	apiDocs: "API documentation",
	apiStudio: "API Studio",
	codeThemes: "Importing code themes",
	developerEnvironment: "The developer environment",
	diagnostics: "The diagnostics folder",
	dmgBuilder: "The DMG builder",
	droppedFiles: "Dropping files",
	extensions: "Managing extensions",
	goToDefinition: "Go to definition",
	lazyShield: "Lazy Shield",
	linting: "Linting and code scans",
	openInEditor: "Opening files in an editor",
	pastedImages: "Pasting images",
	pictureInPicture: "Picture in picture",
	restart: "Restarting Lazify",
	templates: "Managing templates",
	updates: "Updating Lazify",
	uploadPicker: "Choosing a file to upload",
};

const notYet = (feature: string) => new Error(`${feature} isn't available in Lazify Chain yet.`);

const rejects = (feature: string) => () => Promise.reject(notYet(feature));
const throws = (feature: string) => () => {
	throw notYet(feature);
};
const noSubscription = () => () => undefined;
const ignored = () => undefined;

export const lazify: LazifyApi = {
	platform: "darwin",
	signalRendererReady: ignored,
	listScripts: scripts.listScripts,
	runScript: scripts.runScript,
	stopScript: scripts.stopScript,
	restartScript: scripts.restartScript,
	listSessions: scripts.listSessions,
	ptyWrite: scripts.ptyWrite,
	ptyBacklog: scripts.ptyBacklog,
	ptyResize: scripts.ptyResize,
	onPtyData: scripts.onPtyData,
	onScriptStatus: scripts.onScriptStatus,
	onSessionKilled: scripts.onSessionKilled,
	getProjectGitStatus: git.getProjectGitStatus,
	getWorkingChanges: git.getWorkingChanges,
	getFileDiff: git.getFileDiff,
	checkoutBranch: git.checkoutBranch,
	stageFiles: git.stageFiles,
	unstageFiles: git.unstageFiles,
	discardChanges: git.discardChanges,
	commitChanges: git.commitChanges,
	pushBranch: git.pushBranch,
	pullBranch: git.pullBranch,
	importProjectFromDirectory: projects.importProjectFromDirectory,
	importProjectIndexFromDirectory: projects.importProjectIndexFromDirectory,
	readImportedProjectFile: projects.readImportedProjectFile,
	readProjectAssetFile: projects.readProjectAssetFile,
	searchProject: projects.searchProject,
	selectDirectory: projects.selectDirectory,
	selectDirectories: projects.selectDirectories,
	selectPaths: projects.selectPaths,
	runCommand: commands.runCommand,
	chooseCommandOption: commands.chooseCommandOption,
	onLog: commands.onLog,
	onCommandChoicePrompt: commands.onCommandChoicePrompt,
	listAgents: agents.listAgents,
	addCustomAgent: agents.addCustomAgent,
	removeCustomAgent: agents.removeCustomAgent,
	openAgentTerminal: agents.openAgentTerminal,
	onAgentAttention: agents.onAgentAttention,
	onAgentDone: agents.onAgentDone,
	onAgentFocus: agents.onAgentFocus,
	openExternalUrl: system.openExternalUrl,
	revealInFileManager: system.revealInFileManager,
	openTerminal: system.openTerminal,
	onAutopilotAnswered: agents.onAutopilotAnswered,
	listAgentSessions: agents.listAgentSessions,
	autopilotSettings: autopilot.autopilotSettings,
	setAutopilot: autopilot.setAutopilot,
	setAutopilotProject: autopilot.setAutopilotProject,
	keepAwake: keepAwakeGroup.keepAwake,
	setKeepAwake: keepAwakeGroup.setKeepAwake,
	getAgentUsage: agents.getAgentUsage,
	setAgentBudget: agents.setAgentBudget,
	onAgentActivity: agents.onAgentActivity,
	readCollectionDoc: rejects(unported.apiDocs),
	saveCollectionDoc: rejects(unported.apiDocs),
	previewCollectionDoc: rejects(unported.apiDocs),
	openCollectionDoc: rejects(unported.apiDocs),
	exportCollectionDoc: rejects(unported.apiDocs),
	chooseDocLogo: rejects(unported.apiDocs),
	collectionDocBrief: rejects(unported.apiDocs),
	collectionDocQuestions: rejects(unported.apiDocs),
	writeCollectionDocBrief: rejects(unported.apiDocs),
	importCollectionDocDraft: rejects(unported.apiDocs),
	watchCollectionDocDraft: rejects(unported.apiDocs),
	unwatchCollectionDocDraft: rejects(unported.apiDocs),
	onCollectionDocDraftChanged: noSubscription,
	scanProjectRoutes: rejects(unported.apiStudio),
	readProjectRoutes: rejects(unported.apiStudio),
	readRouteDetails: rejects(unported.apiStudio),
	readApiEnvironments: rejects(unported.apiStudio),
	saveApiEnvironments: rejects(unported.apiStudio),
	exportPostmanCollection: rejects(unported.apiStudio),
	readApiRequests: rejects(unported.apiStudio),
	saveApiRequest: rejects(unported.apiStudio),
	forgetApiRequest: rejects(unported.apiStudio),
	readApiResponseBody: rejects(unported.apiStudio),
	readApiCollections: rejects(unported.apiStudio),
	exportCustomCollection: rejects(unported.apiStudio),
	saveResponseFile: rejects(unported.apiStudio),
	openResponseFile: rejects(unported.apiStudio),
	readApiCollectionBody: rejects(unported.apiStudio),
	saveApiCollections: rejects(unported.apiStudio),
	setApiRequestStorage: rejects(unported.apiStudio),
	sendApiRequest: rejects(unported.apiStudio),
	runApiRequest: rejects(unported.apiStudio),
	readAllowedHosts: rejects(unported.apiStudio),
	allowApiHost: rejects(unported.apiStudio),
	forgetApiHost: rejects(unported.apiStudio),
	readScriptSettings: rejects(unported.apiStudio),
	saveScriptSettings: rejects(unported.apiStudio),
	getLazyShieldState: rejects(unported.lazyShield),
	setLazyShield: rejects(unported.lazyShield),
	onLazyShieldBlocked: noSubscription,
	onBrowserSwipeProgress: noSubscription,
	onBrowserOpenTab: noSubscription,
	onBrowserPopupBlocked: noSubscription,
	allowPopupsFrom: rejects(unported.lazyShield),
	findSymbolDefinition: rejects(unported.goToDefinition),
	selectAppBundle: rejects(unported.dmgBuilder),
	selectDmgDestination: rejects(unported.dmgBuilder),
	inspectAppBundle: rejects(unported.dmgBuilder),
	defaultDmgPath: rejects(unported.dmgBuilder),
	selectDmgImage: rejects(unported.dmgBuilder),
	dmgImagePreview: rejects(unported.dmgBuilder),
	compileDmg: rejects(unported.dmgBuilder),
	onDmgProgress: noSubscription,
	listEnvFiles: projects.listProjectEnvFiles,
	readEnvFile: projects.readProjectEnvFile,
	updateEnvVariable: projects.updateEnvVariable,
	deleteEnvVariable: projects.deleteEnvVariable,
	addEnvVariable: projects.addEnvVariable,
	createEnvFile: projects.createProjectEnvFile,
	checkEnvironment: workflow.checkEnvironment,
	scanTools: rejects(unported.developerEnvironment),
	probeTool: rejects(unported.developerEnvironment),
	nvmListVersions: rejects(unported.developerEnvironment),
	installNvm: rejects(unported.developerEnvironment),
	nvmSetDefault: rejects(unported.developerEnvironment),
	nvmUse: rejects(unported.developerEnvironment),
	installTool: rejects(unported.developerEnvironment),
	uninstallTool: rejects(unported.developerEnvironment),
	checkToolUpdate: rejects(unported.developerEnvironment),
	updateTool: rejects(unported.developerEnvironment),
	listListeningProcesses: rejects(unported.developerEnvironment),
	killListeningProcess: rejects(unported.developerEnvironment),
	listExtensions: rejects(unported.extensions),
	installExtension: rejects(unported.extensions),
	extensionInstallJobs: rejects(unported.extensions),
	removeExtension: rejects(unported.extensions),
	toggleExtension: rejects(unported.extensions),
	writeExtensionManifest: rejects(unported.extensions),
	onExtensionInstall: noSubscription,
	formatterSettings: formatting.formatterSettings,
	setFormatterMode: formatting.setFormatterMode,
	setOrganizeImports: formatting.setOrganizeImports,
	setFormatterDefaults: formatting.setFormatterDefaults,
	formatSample: formatting.formatSample,
	projectFormatter: formatting.projectFormatter,
	formatChangedFiles: formatting.formatChangedFiles,
	onCodeFormatted: formatting.onCodeFormatted,
	lintFile: rejects(unported.linting),
	createFixTask: rejects(unported.linting),
	startSonarScan: rejects(unported.linting),
	stopSonarScan: rejects(unported.linting),
	sonarScanState: rejects(unported.linting),
	createPhaseTasks: rejects(unported.linting),
	onSonarScan: noSubscription,
	openPictureInPicture: rejects(unported.pictureInPicture),
	closePictureInPicture: rejects(unported.pictureInPicture),
	getPictureInPictureState: rejects(unported.pictureInPicture),
	onPictureInPictureChanged: noSubscription,
	toggleMediaPictureInPicture: rejects(unported.pictureInPicture),
	searchNpmPackages: packages.searchNpmPackages,
	getNpmOutdated: packages.getNpmOutdated,
	getNpmAudit: packages.getNpmAudit,
	listProjectPackages: packages.listProjectPackages,
	addProjectPackage: packages.addProjectPackage,
	removeProjectPackage: packages.removeProjectPackage,
	installProjectDependencies: packages.installProjectDependencies,
	matchPackageVersions: packages.matchPackageVersions,
	fixProjectPackageVersions: packages.fixProjectPackageVersions,
	listPromptPresets: prompts.listPromptPresets,
	createPromptPreset: prompts.createPromptPreset,
	updatePromptPreset: prompts.updatePromptPreset,
	deletePromptPreset: prompts.deletePromptPreset,
	listContextEntries: prompts.listContextEntries,
	createContextEntry: prompts.createContextEntry,
	updateContextEntry: prompts.updateContextEntry,
	setContextEntryActive: prompts.setContextEntryActive,
	setContextPackActive: prompts.setContextPackActive,
	deleteContextEntry: prompts.deleteContextEntry,
	buildPrompt: prompts.buildPrompt,
	suggestPromptPreset: prompts.suggestPromptPreset,
	relaunchApp: rejects(unported.restart),
	getDiagnosticsPaths: rejects(unported.diagnostics),
	saveClipboardImage: rejects(unported.pastedImages),
	pathForDroppedFile: throws(unported.droppedFiles),
	listHighlightingAssets: rejects(unported.codeThemes),
	openHighlightingFolder: rejects(unported.codeThemes),
	detectEditors: rejects(unported.openInEditor),
	openInEditor: rejects(unported.openInEditor),
	chooseUploadFile: rejects(unported.uploadPicker),
	readZoom: zoom.readZoom,
	setZoom: zoom.setZoom,
	stepZoom: zoom.stepZoom,
	resetZoom: zoom.resetZoom,
	onZoomChanged: zoom.onZoomChanged,
	listTasks: tasks.listTasks,
	listAllTasks: tasks.listAllTasks,
	createTask: tasks.createTask,
	updateTask: tasks.updateTask,
	setTaskStatus: tasks.setTaskStatus,
	listTaskStatusEvents: tasks.listTaskStatusEvents,
	reorderTask: tasks.reorderTask,
	deleteTask: tasks.deleteTask,
	buildTaskPrompt: tasks.buildTaskPrompt,
	recordTaskRun: tasks.recordTaskRun,
	listTaskRuns: tasks.listTaskRuns,
	completeTaskRun: tasks.completeTaskRun,
	completeAgentTaskRuns: tasks.completeAgentTaskRuns,
	listTemplates: workflow.listTemplates,
	listImportedTemplates: rejects(unported.templates),
	getImportedTemplate: rejects(unported.templates),
	updateImportedTemplate: rejects(unported.templates),
	deleteImportedTemplate: rejects(unported.templates),
	getTemplatePackageManifest: workflow.getTemplatePackageManifest,
	saveImportedTemplate: rejects(unported.templates),
	getUpdateState: rejects(unported.updates),
	checkForUpdates: rejects(unported.updates),
	downloadUpdate: rejects(unported.updates),
	quitAndInstallUpdate: rejects(unported.updates),
	onUpdateStateChanged: noSubscription,
	createProject: workflow.createProject,
	installPackage: packages.installPackage,
	onWorkflowProgress: workflow.onWorkflowProgress,
};
