import type { BuildPromptInput, BuiltPrompt, ContextEntry, ContextEntryInput, ContextScope, PromptPreset, PromptPresetInput } from "@/features/prompts/lib/types";
import type { CommandChoicePrompt, LogEvent } from "@/platform/command-runner";
import type { AgentActivityEvent } from "@/shared/lib/agents/agent-activity-watcher";
import type { AgentDescriptor } from "@/shared/lib/agents/agent-registry";
import type { AgentSessionSummary } from "@/shared/lib/agents/agent-sessions";
import type { AutopilotHold } from "@/shared/lib/agents/autopilot-policy";
import type { AutopilotSettings } from "@/shared/lib/agents/autopilot-store";
import type { CustomAgent, CustomAgentInput } from "@/shared/lib/agents/custom-agents-store";
import type { SwipeProgressEvent as BrowserSwipeProgress } from "@/shared/lib/browser/swipe-navigation";
import type { HighlightingAssets } from "@/shared/lib/code-intelligence/highlighting-store";
import type { DiagnosticsPaths } from "@/shared/lib/diagnostics/logger";
import type { AppBundleInfo, DmgProgress, DmgResult } from "@/shared/lib/dmg/types";
import type { NvmInstallResult, NvmVersionList } from "@/shared/lib/environment/nvm-manager";
import type { EnvironmentScan } from "@/shared/lib/environment/scanner";
import type { NvmActionResult } from "@/shared/lib/environment/tool-actions";
import type { ToolScanReport, ToolUpdateInfo } from "@/shared/lib/environment/tools/types";
import type { ExtensionState, InstallJob } from "@/shared/lib/extensions/types";
import type { FormatMode, FormatOutcome, FormatterDefaults, FormatterSettings, ProjectFormatter } from "@/shared/lib/formatting/types";
import type { GitActionResult } from "@/shared/lib/git/git-actions";
import type { GitCheckoutResult } from "@/shared/lib/git/project-git-status";
import type { FixTaskInput } from "@/shared/lib/linting/fix-task";
import type { PhaseTaskRequest } from "@/shared/lib/linting/scan/phase-tasks";
import type { SonarScanState } from "@/shared/lib/linting/scan/types";
import type { LintResult } from "@/shared/lib/linting/types";
import type { VersionMatchReport } from "@/shared/lib/package-version-matcher/types";
import type { ProjectSearchQuery, ProjectSearchResult } from "@/shared/lib/projects/project-search/types";
import type { TemplateDefinition } from "@/shared/lib/scaffolding/harmonizer";
import type { NpmPackageSearchResult } from "@/shared/lib/scaffolding/npm-registry";
import type { TemplatePackageEntry } from "@/shared/lib/scaffolding/template-package-manifest";
import type { AddProjectPackagePayload, CreateProjectPayload, InstallPackagePayload, RemoveProjectPackagePayload, WorkflowProgressEvent, WorkflowResult } from "@/shared/lib/scaffolding/workflow/types";
import type { Task, TaskAgentRun, TaskAgentRunInput, TaskInput, TaskStatus, TaskStatusEvent, TaskStatusSource } from "@/shared/lib/tasks/types";
import type { AgentUsageReport } from "@/shared/types/agents";
import type { EnvFileSummary, EnvVariablePatch, ProjectEnvFile } from "@/shared/types/env";
import type { AgentFileChange, ProjectGitStatusResult } from "@/shared/types/git";
import type { InstalledPackage, NpmAuditResult, NpmOutdatedResult } from "@/shared/types/packages";
import type { ImportedProjectIndexResult, ImportedProjectScanResult, ProjectAssetFile, ProjectTreeNode } from "@/shared/types/project-tree";
import type { PtySession, ScriptStatusEvent } from "@/shared/types/sessions";
import type { ImportedTemplateOption, ImportedTemplateSnapshot } from "@/shared/types/templates";
import type { UpdateState } from "@/shared/types/updates";

export interface LazifyApi {
	onAgentAttention: (callback: (event: {
			runId: string;
			projectPath: string;
			projectName: string;
			agentLabel: string;
			waiting: boolean;
			/** Why autopilot left this prompt to the user, when it looked at it. */
			hold: AutopilotHold | null;
		}) => void) => () => void;
	onAutopilotAnswered: (callback: (event: {
			runId: string;
			projectPath: string;
			projectName: string;
			agentLabel: string;
			question: string;
			optionLabel: string;
		}) => void) => () => void;
	onAgentDone: (callback: (event: {
			runId: string;
			projectPath: string;
			projectName: string;
			agentLabel: string;
		}) => void) => () => void;
	onAgentFocus: (callback: (event: { runId: string; projectPath: string }) => void) => () => void;
	listAgents: () => Promise<AgentDescriptor[]>;
	listAgentSessions: (projectPath: string) => Promise<AgentSessionSummary[]>;
	addCustomAgent: (input: CustomAgentInput) => Promise<CustomAgent>;
	removeCustomAgent: (agentId: string) => Promise<void>;
	autopilotSettings: () => Promise<AutopilotSettings>;
	setAutopilot: (enabled: boolean) => Promise<AutopilotSettings>;
	setAutopilotProject: (projectPath: string, enabled: boolean) => Promise<AutopilotSettings>;
	keepAwake: () => Promise<boolean>;
	setKeepAwake: (enabled: boolean) => Promise<boolean>;
	getAgentUsage: (sinceIso?: string, agentIds?: string[]) => Promise<AgentUsageReport>;
	setAgentBudget: (agentId: string, weeklyTokens: number) => Promise<Record<string, number>>;
	openAgentTerminal: (agentId: string, projectPath: string, cols?: number, rows?: number, resumeSessionId?: string, hidden?: boolean) => Promise<{ runId: string }>;
	onAgentActivity: (callback: (event: AgentActivityEvent) => void) => () => void;
	readCollectionDoc: (projectPath: string, collectionId: string) => Promise<import("@/shared/lib/api-studio/docs/types").DocState | null>;
	saveCollectionDoc: (projectPath: string, doc: import("@/shared/lib/api-studio/docs/types").CollectionDoc) => Promise<import("@/shared/lib/api-studio/docs/types").DocState | null>;
	previewCollectionDoc: (projectPath: string, collectionId: string) => Promise<string | null>;
	openCollectionDoc: (projectPath: string, collectionId: string) => Promise<string | null>;
	exportCollectionDoc: (projectPath: string, collectionId: string, format: import("@/shared/lib/api-studio/docs/types").DocFormat, name: string) => Promise<import("@/shared/lib/api-studio/docs/types").DocExport | null>;
	chooseDocLogo: () => Promise<string | null>;
	collectionDocBrief: (projectPath: string, collectionId: string) => Promise<import("@/shared/lib/api-studio/docs/types").DocBrief | null>;
	collectionDocQuestions: (projectPath: string, collectionId: string, keys: string[]) => Promise<string | null>;
	writeCollectionDocBrief: (projectPath: string, collectionId: string) => Promise<import("@/shared/lib/api-studio/docs/types").DocBriefFiles | null>;
	importCollectionDocDraft: (projectPath: string, collectionId: string, choose: boolean, onlyEmpty?: boolean) => Promise<import("@/shared/lib/api-studio/docs/types").DocImportResult | null>;
	watchCollectionDocDraft: (projectPath: string, collectionId: string) => Promise<boolean>;
	unwatchCollectionDocDraft: (collectionId: string) => Promise<void>;
	onCollectionDocDraftChanged: (callback: (collectionId: string) => void) => () => void;
	scanProjectRoutes: (projectPath: string) => Promise<import("@/shared/lib/api-studio/types").SavedRouteScan>;
	readProjectRoutes: (projectPath: string) => Promise<import("@/shared/lib/api-studio/types").SavedRouteScan | null>;
	readRouteDetails: (projectPath: string, folder: string) => Promise<import("@/shared/lib/api-studio/types").SavedRouteDetail[]>;
	readApiEnvironments: (projectPath: string) => Promise<import("@/shared/lib/api-studio/types").ApiEnvironmentSet>;
	saveApiEnvironments: (projectPath: string, set: import("@/shared/lib/api-studio/types").ApiEnvironmentSet, secretNames: string[]) => Promise<import("@/shared/lib/api-studio/types").ApiEnvironmentSet>;
	exportPostmanCollection: (projectPath: string) => Promise<import("@/shared/lib/api-studio/export/write-collection").CollectionExport | null>;
	readApiRequests: (projectPath: string) => Promise<import("@/shared/lib/api-studio/request-store").RequestStore>;
	saveApiRequest: (projectPath: string, routeId: string, request: import("@/shared/lib/api-studio/request-store").SavedRequest) => Promise<import("@/shared/lib/api-studio/request-store").RequestStore>;
	forgetApiRequest: (projectPath: string, routeId: string) => Promise<import("@/shared/lib/api-studio/request-store").RequestStore>;
	readApiResponseBody: (projectPath: string, bodyFile: string) => Promise<string>;
	readApiCollections: (projectPath: string) => Promise<import("@/shared/lib/api-studio/custom-collections").CustomCollection[]>;
	exportCustomCollection: (projectPath: string, collectionId: string, collectionName: string) => Promise<import("@/shared/lib/api-studio/export/write-collection").CollectionExport | null>;
	saveResponseFile: (filePath: string, suggestedName: string) => Promise<string | null>;
	openResponseFile: (filePath: string) => Promise<string | null>;
	readApiCollectionBody: (projectPath: string, bodyFile: string) => Promise<string>;
	saveApiCollections: (projectPath: string, collections: import("@/shared/lib/api-studio/custom-collections").CustomCollection[]) => Promise<import("@/shared/lib/api-studio/custom-collections").CustomCollection[]>;
	setApiRequestStorage: (projectPath: string, location: import("@/shared/lib/api-studio/request-store").RequestStorage) => Promise<import("@/shared/lib/api-studio/request-store").RequestStore>;
	sendApiRequest: (draft: import("@/shared/lib/api-studio/runner/types").ApiRequestDraft) => Promise<import("@/shared/lib/api-studio/runner/types").ApiSendOutcome>;
	runApiRequest: (input: import("@/shared/lib/api-studio/scripting/types").ScriptedRunInput) => Promise<import("@/shared/lib/api-studio/scripting/types").ApiRunOutcome>;
	readAllowedHosts: (projectPath: string) => Promise<string[]>;
	allowApiHost: (projectPath: string, url: string) => Promise<string[]>;
	forgetApiHost: (projectPath: string, host: string) => Promise<string[]>;
	readScriptSettings: (projectPath: string) => Promise<import("@/shared/lib/api-studio/script-settings").ScriptSettings>;
	saveScriptSettings: (projectPath: string, settings: import("@/shared/lib/api-studio/script-settings").ScriptSettings) => Promise<import("@/shared/lib/api-studio/script-settings").ScriptSettings>;
	getLazyShieldState: () => Promise<import("@/shared/lib/browser/lazy-shield").LazyShieldState>;
	setLazyShield: (enabled: boolean) => Promise<import("@/shared/lib/browser/lazy-shield").LazyShieldState>;
	onLazyShieldBlocked: (callback: (event: { blocked: number }) => void) => () => void;
	onBrowserSwipeProgress: (callback: (event: BrowserSwipeProgress | null) => void) => () => void;
	onBrowserOpenTab: (callback: (event: { url: string; background: boolean }) => void) => () => void;
	onBrowserPopupBlocked: (callback: (event: import("@/shared/lib/browser/popup-policy").BlockedPopup) => void) => () => void;
	allowPopupsFrom: (sourceUrl: string) => Promise<void>;
	findSymbolDefinition: (projectPath: string, symbol: string, fromPath?: string | null, position?: { line: number; column: number } | null) => Promise<import("@/shared/lib/code-intelligence/symbol-finder").SymbolDefinition | null>;
	selectAppBundle: () => Promise<string | null>;
	selectDmgDestination: (suggestedPath: string) => Promise<string | null>;
	inspectAppBundle: (appPath: string) => Promise<AppBundleInfo>;
	defaultDmgPath: (appPath: string, suggestedFileName: string) => Promise<string>;
	selectDmgImage: (kind: "background" | "icon") => Promise<string | null>;
	dmgImagePreview: (imagePath: string, maxPixels?: number) => Promise<string | null>;
	compileDmg: (appPath: string, outputPath: string, volumeName?: string | null, backgroundImagePath?: string | null, volumeIconPath?: string | null) => Promise<DmgResult>;
	onDmgProgress: (callback: (progress: DmgProgress) => void) => () => void;
	listEnvFiles: (projectPath: string) => Promise<EnvFileSummary[]>;
	readEnvFile: (projectPath: string, fileName: string) => Promise<ProjectEnvFile>;
	updateEnvVariable: (projectPath: string, fileName: string, line: number, expectedKey: string, patch: EnvVariablePatch) => Promise<ProjectEnvFile>;
	deleteEnvVariable: (projectPath: string, fileName: string, line: number, expectedKey: string) => Promise<ProjectEnvFile>;
	addEnvVariable: (projectPath: string, fileName: string, key: string, value: string) => Promise<ProjectEnvFile>;
	createEnvFile: (projectPath: string, fileName: string) => Promise<ProjectEnvFile>;
	checkEnvironment: () => Promise<EnvironmentScan>;
	scanTools: (force?: boolean) => Promise<ToolScanReport>;
	probeTool: (name: string) => Promise<import("@/shared/lib/environment/tools/types").DetectedTool | null>;
	nvmListVersions: () => Promise<NvmVersionList>;
	installNvm: () => Promise<NvmInstallResult>;
	nvmSetDefault: (version: string) => Promise<NvmActionResult>;
	nvmUse: (version: string) => Promise<NvmActionResult>;
	installTool: (toolName: string) => Promise<NvmActionResult>;
	uninstallTool: (toolName: string) => Promise<NvmActionResult>;
	checkToolUpdate: (toolName: string, currentVersion: string) => Promise<ToolUpdateInfo>;
	updateTool: (toolName: string) => Promise<NvmActionResult>;
	listListeningProcesses: () => Promise<
		import("@/shared/lib/environment/port-reaper").ListeningProcess[]
	>;
	killListeningProcess: (pid: number) => Promise<import("@/shared/lib/environment/port-reaper").KillResult>;
	listExtensions: (refresh?: boolean) => Promise<ExtensionState[]>;
	installExtension: (id: string) => Promise<InstallJob>;
	extensionInstallJobs: () => Promise<InstallJob[]>;
	removeExtension: (id: string) => Promise<ExtensionState[]>;
	toggleExtension: (id: string, enabled: boolean) => Promise<ExtensionState[]>;
	writeExtensionManifest: (projectPath: string) => Promise<string | null>;
	onExtensionInstall: (callback: (job: InstallJob) => void) => () => void;
	formatterSettings: () => Promise<FormatterSettings>;
	setFormatterMode: (mode: FormatMode) => Promise<FormatterSettings>;
	setOrganizeImports: (enabled: boolean) => Promise<FormatterSettings>;
	setFormatterDefaults: (defaults: Partial<FormatterDefaults>) => Promise<FormatterSettings>;
	formatSample: (defaults: FormatterDefaults) => Promise<string>;
	projectFormatter: (projectPath: string) => Promise<ProjectFormatter>;
	formatChangedFiles: (projectPath: string, only?: string[], mode?: "write" | "preview") => Promise<FormatOutcome>;
	onCodeFormatted: (callback: (event: FormatOutcome & { projectPath: string }) => void) => () => void;
	getProjectGitStatus: (projectPath: string) => Promise<ProjectGitStatusResult>;
	getWorkingChanges: (projectPath: string) => Promise<AgentFileChange[]>;
	getFileDiff: (projectPath: string, filePath: string, fullFile?: boolean) => Promise<string>;
	checkoutBranch: (projectPath: string, branch: string) => Promise<GitCheckoutResult>;
	stageFiles: (projectPath: string, paths: string[]) => Promise<GitActionResult>;
	unstageFiles: (projectPath: string, paths: string[]) => Promise<GitActionResult>;
	discardChanges: (projectPath: string, paths: string[]) => Promise<GitActionResult>;
	commitChanges: (projectPath: string, message: string) => Promise<GitActionResult>;
	pushBranch: (projectPath: string) => Promise<GitActionResult>;
	pullBranch: (projectPath: string) => Promise<GitActionResult>;
	lintFile: (filePath: string, content: string) => Promise<LintResult>;
	createFixTask: (input: FixTaskInput) => Promise<Task | null>;
	startSonarScan: (projectPath: string) => Promise<SonarScanState>;
	stopSonarScan: (projectPath: string) => Promise<SonarScanState>;
	sonarScanState: (projectPath: string) => Promise<SonarScanState>;
	createPhaseTasks: (request: PhaseTaskRequest) => Promise<Task[]>;
	onSonarScan: (callback: (state: SonarScanState) => void) => () => void;
	openPictureInPicture: (url: string, source: import("@/shared/lib/media/picture-in-picture").PictureInPictureSource) => Promise<import("@/shared/lib/media/picture-in-picture").PictureInPictureState>;
	closePictureInPicture: () => Promise<
		import("@/shared/lib/media/picture-in-picture").PictureInPictureState
	>;
	getPictureInPictureState: () => Promise<
		import("@/shared/lib/media/picture-in-picture").PictureInPictureState
	>;
	onPictureInPictureChanged: (callback: (state: import("@/shared/lib/media/picture-in-picture").PictureInPictureState) => void) => () => void;
	toggleMediaPictureInPicture: (webContentsId: number) => Promise<import("@/shared/lib/media/media-pip").MediaPipResult>;
	searchNpmPackages: (query: string) => Promise<NpmPackageSearchResult[]>;
	getNpmOutdated: (projectPath: string) => Promise<NpmOutdatedResult>;
	getNpmAudit: (projectPath: string) => Promise<NpmAuditResult>;
	listProjectPackages: (projectPath: string) => Promise<InstalledPackage[]>;
	addProjectPackage: (payload: AddProjectPackagePayload) => Promise<WorkflowResult>;
	removeProjectPackage: (payload: RemoveProjectPackagePayload) => Promise<WorkflowResult>;
	installProjectDependencies: (projectPath: string) => Promise<WorkflowResult>;
	matchPackageVersions: (projectPath: string) => Promise<VersionMatchReport>;
	fixProjectPackageVersions: (projectPath: string) => Promise<import("@/shared/lib/scaffolding/workflow/types").WorkflowResult>;
	importProjectFromDirectory: (projectPath: string) => Promise<ImportedProjectScanResult>;
	importProjectIndexFromDirectory: (projectPath: string) => Promise<ImportedProjectIndexResult>;
	readImportedProjectFile: (filePath: string) => Promise<string>;
	readProjectAssetFile: (filePath: string) => Promise<ProjectAssetFile>;
	searchProject: (projectPath: string, query: ProjectSearchQuery) => Promise<ProjectSearchResult>;
	listPromptPresets: () => Promise<PromptPreset[]>;
	createPromptPreset: (input: PromptPresetInput) => Promise<PromptPreset>;
	updatePromptPreset: (id: string, input: PromptPresetInput) => Promise<PromptPreset | null>;
	deletePromptPreset: (id: string) => Promise<boolean>;
	listContextEntries: (projectPath: string) => Promise<ContextEntry[]>;
	createContextEntry: (input: ContextEntryInput) => Promise<ContextEntry>;
	updateContextEntry: (id: string, input: ContextEntryInput) => Promise<boolean>;
	setContextEntryActive: (id: string, active: boolean) => Promise<boolean>;
	setContextPackActive: (scope: ContextScope, scopeKey: string, pack: string, active: boolean) => Promise<number>;
	deleteContextEntry: (id: string) => Promise<boolean>;
	buildPrompt: (input: BuildPromptInput) => Promise<BuiltPrompt>;
	suggestPromptPreset: (text: string) => Promise<string | null>;
	listScripts: (projectPath: string) => Promise<Record<string, string>>;
	runScript: (projectPath: string, scriptName: string, cols?: number, rows?: number) => Promise<{ runId: string; ptyAvailable: boolean }>;
	stopScript: (runId: string) => Promise<void>;
	restartScript: (runId: string, projectPath: string, scriptName: string, cols?: number, rows?: number) => Promise<{ runId: string; ptyAvailable: boolean }>;
	listSessions: () => Promise<PtySession[]>;
	ptyWrite: (runId: string, data: string) => void;
	ptyBacklog: (runId: string) => Promise<import("@/platform/terminal").PtyBacklog>;
	ptyResize: (runId: string, cols: number, rows: number) => void;
	onPtyData: (callback: (event: import("@/platform/terminal").PtyDataEvent) => void) => () => void;
	onScriptStatus: (callback: (event: ScriptStatusEvent) => void) => () => void;
	onSessionKilled: (callback: (event: { runId: string }) => void) => () => void;
	platform: string;
	runCommand: (command: string, args: string[], cwd?: string) => Promise<any>;
	chooseCommandOption: (promptId: string, optionId: string) => Promise<boolean>;
	relaunchApp: () => Promise<void>;
	signalRendererReady: () => void;
	selectDirectory: () => Promise<string | null>;
	selectDirectories: () => Promise<string[]>;
	selectPaths: (defaultPath?: string | null) => Promise<string[]>;
	getDiagnosticsPaths: () => Promise<DiagnosticsPaths>;
	saveClipboardImage: () => Promise<string | null>;
	pathForDroppedFile: (file: File) => string;
	listHighlightingAssets: () => Promise<HighlightingAssets>;
	openHighlightingFolder: () => Promise<void>;
	revealInFileManager: (targetPath: string) => Promise<void>;
	detectEditors: () => Promise<import("@/shared/lib/environment/editor-catalog").DetectedEditor[]>;
	openInEditor: (request: import("@/shared/lib/environment/open-in-editor").OpenInEditorRequest) => Promise<import("@/shared/lib/environment/open-in-editor").OpenInEditorResult>;
	openTerminal: (targetPath: string) => Promise<void>;
	openExternalUrl: (url: string) => Promise<void>;
	chooseUploadFile: () => Promise<string | null>;
	readZoom: () => Promise<number>;
	setZoom: (factor: number) => Promise<number>;
	stepZoom: (direction: 1 | -1) => Promise<number>;
	resetZoom: () => Promise<number>;
	onZoomChanged: (callback: (factor: number) => void) => () => void;
	onLog: (callback: (event: LogEvent) => void) => () => void;
	onCommandChoicePrompt: (callback: (prompt: CommandChoicePrompt) => void) => () => void;
	listTasks: (projectPath: string) => Promise<Task[]>;
	listAllTasks: () => Promise<Task[]>;
	createTask: (input: TaskInput) => Promise<Task>;
	updateTask: (id: string, input: TaskInput) => Promise<boolean>;
	setTaskStatus: (id: string, status: TaskStatus, source?: TaskStatusSource) => Promise<boolean>;
	listTaskStatusEvents: (taskId: string) => Promise<TaskStatusEvent[]>;
	reorderTask: (id: string, sortOrder: number) => Promise<boolean>;
	deleteTask: (id: string) => Promise<boolean>;
	buildTaskPrompt: (taskId: string) => Promise<BuiltPrompt | null>;
	recordTaskRun: (input: TaskAgentRunInput) => Promise<TaskAgentRun>;
	listTaskRuns: (taskId: string) => Promise<TaskAgentRun[]>;
	completeTaskRun: (id: string) => Promise<boolean>;
	completeAgentTaskRuns: (agentRunId: string) => Promise<number>;
	listTemplates: () => Promise<TemplateDefinition[]>;
	listImportedTemplates: () => Promise<ImportedTemplateOption[]>;
	getImportedTemplate: (templateId: string) => Promise<ImportedTemplateSnapshot>;
	updateImportedTemplate: (templateId: string, updates: { name?: string | null; tree?: ProjectTreeNode[] | null }) => Promise<ImportedTemplateSnapshot>;
	deleteImportedTemplate: (templateId: string) => Promise<void>;
	getTemplatePackageManifest: (templateId: string) => Promise<TemplatePackageEntry[]>;
	saveImportedTemplate: (projectPath: string, includedRelativePaths: string[], providedName?: string | null, confirmedStack?: string | null) => Promise<ImportedTemplateSnapshot>;
	getUpdateState: () => Promise<UpdateState>;
	checkForUpdates: () => Promise<UpdateState>;
	downloadUpdate: () => Promise<UpdateState>;
	quitAndInstallUpdate: () => Promise<void>;
	onUpdateStateChanged: (callback: (state: UpdateState) => void) => () => void;
	createProject: (payload: CreateProjectPayload) => Promise<WorkflowResult>;
	installPackage: (payload: InstallPackagePayload) => Promise<WorkflowResult>;
	onWorkflowProgress: (callback: (event: WorkflowProgressEvent) => void) => () => void;
}
